
site:
  tab: Plesa Alexandru
  title: Blog Plesa Alexandru
  description: Personal Blog for CyberSecurity Writeups, Projects and more.
  language: en
  favicon: /favicon.ico 
  theme:
    light: winter
    dark: night
    code: github-dark 
  date_format: ddd MMM DD YYYY 
  blog: 
    pageSize: 8
  menu: 
    - id: home 
      text: Home 
      href: / 
      svg: "material-symbols:home-outline-rounded"
      target: _self
    - id: about
      text: About
      href: /about
      svg: "material-symbols:info-outline-rounded"
      target: _self
    - id: blog
      text: Blogs
      href: /blog
      svg: "material-symbols:book-2-outline-rounded"
      target: _self
      subItems:
        - id: all
          text: All blogs
          href: /blog
          svg: "material-symbols:ink-pen-outline-rounded"
          target: _self
        - id: documentation
          text: Documentation
          href: /blog/category/Documentation
          svg: "material-symbols:unknown-document-outline-rounded"
          target: _self
        - id: examples
          text: Examples
          href: /blog/category/Examples
          svg: "material-symbols:deployed-code-outline"
          target: _self
       
    - id: project
      text: Projects
      href: /project
      svg: "material-symbols:code-blocks-outline"
      target: _self
    - id: contact
      text: Contact
      href: /contact
      target: _self
      svg: "material-symbols:attach-email-outline-rounded"


user:
  name: PlesaAlexandru 
  site: "https://plesaalexandru.github.io" 
  avatar: /GITHUB1.png
  
  sidebar:
    social:
    - href: "https://github.com/PlesaAlexandru"
      ariaLabel: "GitHub"
      title: "GitHub"
      svg: "ri:github-fill"
    - href: "https://linkedin.com/in/"
      ariaLabel: "LinkedIn"
      title: "LinkedIn"
      svg: "ri:linkedin-box-fill"
    - href: "https://tryhackme.com/p/"
      ariaLabel: "TryHackMe"
      title: "TryHackMe"
      svg: "simple-icons:tryhackme"
    - href: "https://app.hackthebox.com/profile/"
      ariaLabel: "Hack The Box"
      title: "Hack The Box"
      svg: "simple-icons:hackthebox"
    - href: "https://app.letsdefend.io/user/"
      ariaLabel: "LetsDefend"
      title: "LetsDefend"
      svg: "ri:shield-keyhole-line"
  footer:
    social:
      - href: "https://afdian.com/a/saroprock" 
        ariaLabel: Support my work 
        title: Support my work 
        svg: "ri:cup-line"
      - href: "https://github.com/EveSunMaple"
        ariaLabel: Github
        title: Github
        svg: "ri:github-line"
      - href: "https://space.bilibili.com/438392347"
        ariaLabel: BiliBili
        title: BiliBili
        svg: "ri:bilibili-line"
      - href: "https://x.com/EveSunMaple"
        ariaLabel: X(twitter)
        title: X(twitter)
        svg: "ri:twitter-line"
